# SPDX-License-Identifier: CC0-1.0
# PR labeler configuration for misslite-cf

'patches':
- any:
  - changed-files:
    - any-glob-to-any-file: ['patches/**/*']

'worker':
- any:
  - changed-files:
    - any-glob-to-any-file: ['worker/**/*']

'worker:test':
- any:
  - changed-files:
    - any-glob-to-any-file: ['worker/src/__tests__/**/*']

'build':
- any:
  - changed-files:
    - any-glob-to-any-file: ['build.sh', 'patches/**/*']

'ci':
- any:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*']

'api':
- any:
  - changed-files:
    - any-glob-to-any-file: ['api.json']
