/*
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Stub handlers for Misskey API endpoints not yet implemented in MissLite.
 * Each returns the minimum response shape the OpenAPI spec requires so the
 * Misskey frontend loads without errors.
 */

import type { Handler } from '../types.js';
import { json, requireUser } from '../helpers.js';

/* ── generic factories ─────────────────────────────────────────────────── */

const noContent: Handler = async (db, body) => {
	const u = await requireUser(db, body);
	if (u instanceof Response) return u;
	return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': '*' } });
};

const noContentPublic: Handler = async () =>
	new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': '*' } });

const emptyArray: Handler = async (db, body) => {
	const u = await requireUser(db, body);
	if (u instanceof Response) return u;
	return json([]);
};

const emptyArrayPublic: Handler = async () => json([]);

const emptyObject: Handler = async (db, body) => {
	const u = await requireUser(db, body);
	if (u instanceof Response) return u;
	return json({});
};

const emptyObjectPublic: Handler = async () => json({});

function staticJson(value: unknown): Handler {
	return async (db, body) => {
		const u = await requireUser(db, body);
		if (u instanceof Response) return u;
		return json(value);
	};
}

function staticJsonPublic(value: unknown): Handler {
	return async () => json(value);
}

/* ── shared response shapes ─────────────────────────────────────────── */

const ME_DETAILED_STUB = { achievements: null, alsoKnownAs: null, alwaysMarkNsfw: null, autoAcceptFollowed: null, autoSensitive: null, avatarBlurhash: null, avatarDecorations: null, avatarId: null, avatarUrl: null, bannerBlurhash: null, bannerId: null, bannerUrl: null, birthday: null, canChat: null, carefulBot: null, chatScope: null, createdAt: null, description: null, emailNotificationTypes: null, emojis: null, fields: null, followedMessage: null, followersCount: null, followersVisibility: null, followingCount: null, followingVisibility: null, hasPendingReceivedFollowRequest: null, hasUnreadAnnouncement: null, hasUnreadAntenna: null, hasUnreadChannel: null, hasUnreadChatMessages: null, hasUnreadMentions: null, hasUnreadNotification: null, hasUnreadSpecifiedNotes: null, hideOnlineStatus: null, host: null, id: null, injectFeaturedNote: null, isAdmin: null, isDeleted: null, isExplorable: null, isLimited: null, isLocked: null, isModerator: null, isSilenced: null, isSuspended: null, lang: null, lastFetchedAt: null, location: null, loggedInDays: null, memo: null, movedTo: null, mutedInstances: null, mutedWords: null, mutualLinkSections: null, name: null, noCrawle: null, notesCount: null, notificationRecieveConfig: null, onlineStatus: null, pinnedNoteIds: null, pinnedNotes: null, pinnedPage: null, pinnedPageId: null, policies: null, postingLang: null, preventAiLearning: null, publicReactions: null, receiveAnnouncementEmail: null, roles: null, securityKeys: null, showHashtagsInAllLanguages: null, showMediaInAllLanguages: null, twoFactorBackupCodesStock: null, twoFactorEnabled: null, unreadAnnouncements: null, unreadNotificationsCount: null, updatedAt: null, uri: null, url: null, usePasswordLessLogin: null, username: null, verifiedLinks: null, viewingLangs: null };
const USER_LITE_STUB = { alsoKnownAs: null, avatarBlurhash: null, avatarDecorations: [], avatarUrl: null, bannerBlurhash: null, bannerUrl: null, birthday: null, canChat: false, chatScope: '', createdAt: '', description: null, emojis: {}, fields: [], followersCount: 0, followersVisibility: '', followingCount: 0, followingVisibility: '', host: null, id: '', isLimited: false, isLocked: false, isSilenced: false, isSuspended: false, lang: null, lastFetchedAt: null, location: null, memo: null, movedTo: null, mutualLinkSections: [], name: null, notesCount: 0, onlineStatus: '', pinnedNoteIds: [], pinnedNotes: [], pinnedPage: null, pinnedPageId: null, publicReactions: false, roles: [], updatedAt: null, uri: null, url: null, username: '', verifiedLinks: [] };
const USER_LITE_STUB = { avatarBlurhash: null, avatarDecorations: [], avatarUrl: null, emojis: {}, host: null, id: '', name: null, onlineStatus: '', username: '' };
const SHAPE_1 = { local: {}, remote: {} };
const SHAPE_2 = { createdAt: '', id: '', isPublic: false, name: '' };
const SHAPE_3 = { id: '', isActive: false, method: '', name: '', updatedAt: '' };
const SHAPE_4 = { asBadge: false, badgeBehavior: null, canEditMembersByModerator: false, color: null, condFormula: null, createdAt: '', description: '', displayOrder: 0, iconUrl: null, id: '', isAdministrator: false, isExplorable: false, isModerator: false, isPublic: false, name: '', policies: {}, preserveAssignmentOnMoveAccount: false, target: '', updatedAt: '', usersCount: 0 };
const SHAPE_5 = { id: '', isActive: false, latestSentAt: null, latestStatus: null, name: '', on: [], secret: '', updatedAt: '', url: '' };
const SHAPE_6 = { caseSensitive: false, createdAt: '', excludeBots: false, excludeKeywords: [], excludeNotesInSensitiveChannel: false, hasUnreadNote: false, id: '', isActive: false, keywords: [], localOnly: false, name: '', notify: false, src: '', userListId: null, users: [], withFile: false, withReplies: false };
const SHAPE_7 = { allowRenoteToExternal: false, bannerUrl: null, color: '', createdAt: '', description: null, id: '', isArchived: false, isSensitive: false, lastNotedAt: null, name: '', notesCount: 0, pinnedNoteIds: [], userId: null, usersCount: 0 };
const SHAPE_8 = { createdAt: '', description: null, favoritedCount: 0, id: '', isPublic: false, lastClippedAt: null, name: '', user: null, userId: '' };
const SHAPE_9 = { blurhash: null, comment: null, createdAt: '', folderId: null, id: '', isSensitive: false, md5: '', name: '', properties: {}, size: 0, thumbnailUrl: null, type: '', url: '', userId: null };
const SHAPE_10 = { createdAt: '', id: '', name: '', parentId: null };
const SHAPE_11 = { createdAt: '', description: null, id: '', isSensitive: false, likedCount: 0, title: '', updatedAt: '', user: null, userId: '' };
const SHAPE_12 = { aliases: [], category: null, host: null, id: '', isSensitive: false, license: null, localOnly: false, name: '', url: '' };
const SHAPE_13 = { closeDuration: 0, createdAt: '', display: '', displayOrder: 0, forYou: false, icon: '', id: '', imageUrl: null, needConfirmationToRead: false, needEnrollmentTutorialToRead: false, silence: false, text: '', title: '', updatedAt: null };
const SHAPE_14 = { callbackUrl: null, id: '', name: '', permission: [] };
const SHAPE_15 = { createdAt: '', id: '', likedCount: null, script: '', summary: '', title: '', updatedAt: '', user: null, userId: '', visibility: '' };
const SHAPE_16 = { active: false, id: '', latestSentAt: null, latestStatus: null, name: '', on: [], secret: '', url: '', userId: '' };
const SHAPE_17 = { alignCenter: false, attachedFiles: [], content: [], createdAt: '', eyeCatchingImage: null, eyeCatchingImageId: null, font: '', hideTitleWhenPinned: false, id: '', likedCount: 0, name: '', script: '', summary: null, title: '', updatedAt: '', user: null, userId: '', variables: [], visibility: '' };

/* ── stub routes ────────────────────────────────────────────────────── */

export const stubRoutes: Record<string, Handler> = {
	// 204 No Content (authenticated)
	'admin/abuse-report-resolver/delete': noContent,
	'admin/abuse-report-resolver/update': noContent,
	'admin/abuse-report/notification-recipient/delete': noContent,
	'admin/accounts/delete': noContent,
	'admin/accounts/pending/revoke': noContent,
	'admin/ad/delete': noContent,
	'admin/ad/update': noContent,
	'admin/announcements/update': noContent,
	'admin/avatar-decorations/delete': noContent,
	'admin/avatar-decorations/update': noContent,
	'admin/captcha/save': noContent,
	'admin/drive/clean-remote-files': noContent,
	'admin/drive/cleanup': noContent,
	'admin/drive/delete-all-files-of-a-user': noContent,
	'admin/emoji/add-aliases-bulk': noContent,
	'admin/emoji/delete': noContent,
	'admin/emoji/delete-bulk': noContent,
	'admin/emoji/import-zip': noContent,
	'admin/emoji/remove-aliases-bulk': noContent,
	'admin/emoji/set-aliases-bulk': noContent,
	'admin/emoji/set-category-bulk': noContent,
	'admin/emoji/set-license-bulk': noContent,
	'admin/emoji/update': noContent,
	'admin/federation/delete-all-files': noContent,
	'admin/federation/refresh-remote-instance-metadata': noContent,
	'admin/federation/remove-all-following': noContent,
	'admin/federation/update-instance': noContent,
	'admin/forward-abuse-user-report': noContent,
	'admin/indie-auth/delete': noContent,
	'admin/indie-auth/update': noContent,
	'admin/promo/create': noContent,
	'admin/queue/clear': noContent,
	'admin/queue/promote': noContent,
	'admin/regenerate-user-token': noContent,
	'admin/relays/remove': noContent,
	'admin/resolve-abuse-user-report': noContent,
	'admin/roles/assign': noContent,
	'admin/roles/delete': noContent,
	'admin/roles/unassign': noContent,
	'admin/roles/update': noContent,
	'admin/roles/update-default-policies': noContent,
	'admin/roles/update-inline-policies': noContent,
	'admin/send-email': noContent,
	'admin/sso/delete': noContent,
	'admin/sso/update': noContent,
	'admin/system-webhook/delete': noContent,
	'admin/system-webhook/test': noContent,
	'admin/unset-user-avatar': noContent,
	'admin/unset-user-banner': noContent,
	'admin/unset-user-mutual-link': noContent,
	'admin/update-abuse-user-report': noContent,
	'admin/update-user-name': noContent,
	'admin/update-user-note': noContent,
	'antennas/delete': noContent,
	'auth/accept': noContent,
	'bubble-game/register': noContent,
	'channels/favorite': noContent,
	'channels/follow': noContent,
	'channels/unfavorite': noContent,
	'channels/unfollow': noContent,
	'clips/add-note': noContent,
	'clips/delete': noContent,
	'clips/favorite': noContent,
	'clips/remove-note': noContent,
	'clips/unfavorite': noContent,
	'drive/files/delete': noContent,
	'drive/files/upload-from-url': noContent,
	'drive/folders/delete': noContent,
	'export-custom-emojis': noContent,
	'flash/delete': noContent,
	'flash/like': noContent,
	'flash/unlike': noContent,
	'flash/update': noContent,
	'following/requests/accept': noContent,
	'following/requests/reject': noContent,
	'following/update-all': noContent,
	'gallery/posts/delete': noContent,
	'gallery/posts/like': noContent,
	'gallery/posts/unlike': noContent,
	'i/2fa/password-less': noContent,
	'i/2fa/remove-key': noContent,
	'i/2fa/unregister': noContent,
	'i/2fa/update-key': noContent,
	'i/delete-account': noContent,
	'i/export-antennas': noContent,
	'i/export-blocking': noContent,
	'i/export-clips': noContent,
	'i/export-favorites': noContent,
	'i/export-following': noContent,
	'i/export-mute': noContent,
	'i/export-notes': noContent,
	'i/export-user-lists': noContent,
	'i/import-antennas': noContent,
	'i/import-blocking': noContent,
	'i/import-following': noContent,
	'i/import-muting': noContent,
	'i/import-user-lists': noContent,
	'i/purge-timeline-cache': noContent,
	'i/regenerate-token': noContent,
	'i/revoke-token': noContent,
	'i/webhooks/delete': noContent,
	'i/webhooks/test': noContent,
	'i/webhooks/update': noContent,
	'invite/delete': noContent,
	'mute/create': noContent,
	'mute/delete': noContent,
	'notes/polls/vote': noContent,
	'notes/scheduled/cancel': noContent,
	'notes/thread-muting/create': noContent,
	'notes/thread-muting/delete': noContent,
	'notes/translate': noContent,
	'notes/unrenote': noContent,
	'notifications/create': noContent,
	'notifications/flush': noContent,
	'notifications/test-notification': noContent,
	'page-push': noContent,
	'pages/delete': noContent,
	'pages/like': noContent,
	'pages/unlike': noContent,
	'pages/update': noContent,
	'promo/read': noContent,
	'renote-mute/create': noContent,
	'renote-mute/delete': noContent,
	'reversi/cancel-match': noContent,
	'reversi/match': noContent,
	'reversi/surrender': noContent,
	'sw/show-registration': noContent,
	'users/lists/delete': noContent,
	'users/lists/favorite': noContent,
	'users/lists/pull': noContent,
	'users/lists/push': noContent,
	'users/lists/unfavorite': noContent,
	'users/lists/update-membership': noContent,
	'users/report-abuse': noContent,
	'users/update-memo': noContent,
	// 204 No Content (public)
	'endpoint': noContentPublic,
	'federation/show-instance': noContentPublic,
	'federation/update-remote-user': noContentPublic,
	'request-reset-password': noContentPublic,
	'reset-db': noContentPublic,
	'reset-password': noContentPublic,
	// Empty array (authenticated)
	'admin/abuse-report-resolver/list': emptyArray,
	'admin/abuse-report/notification-recipient/list': emptyArray,
	'admin/abuse-user-reports': emptyArray,
	'admin/accounts/pending/list': emptyArray,
	'admin/ad/list': emptyArray,
	'admin/announcements/list': emptyArray,
	'admin/avatar-decorations/list': emptyArray,
	'admin/drive/files': emptyArray,
	'admin/emoji/list': emptyArray,
	'admin/emoji/list-remote': emptyArray,
	'admin/get-index-stats': emptyArray,
	'admin/get-user-ips': emptyArray,
	'admin/indie-auth/list': emptyArray,
	'admin/invite/create': emptyArray,
	'admin/invite/list': emptyArray,
	'admin/queue/deliver-delayed': emptyArray,
	'admin/queue/inbox-delayed': emptyArray,
	'admin/relays/list': emptyArray,
	'admin/roles/list': emptyArray,
	'admin/show-user-account-move-logs': emptyArray,
	'admin/sso/list': emptyArray,
	'admin/system-webhook/list': emptyArray,
	'antennas/notes': emptyArray,
	'blocking/list': emptyArray,
	'channels/my-favorites': emptyArray,
	'channels/owned': emptyArray,
	'clips/list': emptyArray,
	'clips/my-favorites': emptyArray,
	'drive/files/attached-notes': emptyArray,
	'drive/files/find': emptyArray,
	'drive/files/find-by-hash': emptyArray,
	'drive/folders/find': emptyArray,
	'drive/stream': emptyArray,
	'flash/my': emptyArray,
	'flash/my-likes': emptyArray,
	'following/requests/list': emptyArray,
	'following/requests/sent': emptyArray,
	'i/apps': emptyArray,
	'i/authorized-apps': emptyArray,
	'i/gallery/posts': emptyArray,
	'i/page-likes': emptyArray,
	'i/pages': emptyArray,
	'i/registry/scopes-with-domain': emptyArray,
	'i/signin-history': emptyArray,
	'i/webhooks/list': emptyArray,
	'mute/list': emptyArray,
	'my/apps': emptyArray,
	'notes/polls/recommendation': emptyArray,
	'notes/scheduled/list': emptyArray,
	'notes/user-list-timeline': emptyArray,
	'renote-mute/list': emptyArray,
	'reversi/invitations': emptyArray,
	'roles/list': emptyArray,
	'roles/notes': emptyArray,
	'users/get-following-birthday-users': emptyArray,
	'users/recommendation': emptyArray,
	// Empty array (public)
	'admin/roles/users': emptyArrayPublic,
	'channels/featured-games': emptyArrayPublic,
	'channels/search': emptyArrayPublic,
	'channels/timeline': emptyArrayPublic,
	'clips/notes': emptyArrayPublic,
	'federation/followers': emptyArrayPublic,
	'federation/following': emptyArrayPublic,
	'federation/instances': emptyArrayPublic,
	'federation/users': emptyArrayPublic,
	'gallery/popular': emptyArrayPublic,
	'gallery/posts': emptyArrayPublic,
	'get-avatar-decorations': emptyArrayPublic,
	'hashtags/list': emptyArrayPublic,
	'hashtags/search': emptyArrayPublic,
	'hashtags/users': emptyArrayPublic,
	'notes': emptyArrayPublic,
	'notes/children': emptyArrayPublic,
	'notes/clips': emptyArrayPublic,
	'notes/renotes': emptyArrayPublic,
	'notes/replies': emptyArrayPublic,
	'notes/search-by-tag': emptyArrayPublic,
	'pinned-users': emptyArrayPublic,
	'retention': emptyArrayPublic,
	'reversi/games': emptyArrayPublic,
	'roles/users': emptyArrayPublic,
	'users': emptyArrayPublic,
	'users/achievements': emptyArrayPublic,
	'users/clips': emptyArrayPublic,
	'users/featured-notes': emptyArrayPublic,
	'users/flashs': emptyArrayPublic,
	'users/followers': emptyArrayPublic,
	'users/following': emptyArrayPublic,
	'users/gallery/posts': emptyArrayPublic,
	'users/get-frequently-replied-users': emptyArrayPublic,
	'users/lists/get-memberships': emptyArrayPublic,
	'users/pages': emptyArrayPublic,
	'users/reactions': emptyArrayPublic,
	'users/search-by-username-and-host': emptyArrayPublic,
	// Empty object (authenticated)
	'admin/get-table-stats': emptyObject,
	'ap/get': emptyObject,
	'i/move': emptyObject,
	'i/registry/keys-with-type': emptyObject,
	// Objects with required fields
	'admin/abuse-report-resolver/create': staticJson({ expiresAt: '', forward: false, name: '', reportContentPattern: null, reporterPattern: null, targetUserPattern: null }),
	'admin/abuse-report/notification-recipient/create': staticJson(SHAPE_3),
	'admin/abuse-report/notification-recipient/show': staticJson(SHAPE_3),
	'admin/abuse-report/notification-recipient/update': staticJson(SHAPE_3),
	'admin/accounts/find-by-email': staticJson(ME_DETAILED_STUB),
	'admin/ad/create': staticJson({ dayOfWeek: 0, expiresAt: '', id: '', imageBlurhash: null, imageUrl: '', isSensitive: false, memo: '', place: '', priority: '', ratio: 0, startsAt: '', url: '' }),
	'admin/avatar-decorations/create': staticJson({ createdAt: '', description: '', id: '', name: '', roleIdsThatCanBeUsedThisDecoration: [], updatedAt: null, url: '' }),
	'admin/captcha/current': staticJson({ hcaptcha: {}, mcaptcha: {}, provider: '', recaptcha: {}, turnstile: {} }),
	'admin/drive/show-file': staticJson({ accessKey: null, blurhash: null, comment: null, createdAt: '', folderId: null, id: '', isLink: false, isSensitive: false, md5: '', name: '', properties: {}, size: 0, src: null, storedInternal: null, thumbnailAccessKey: null, thumbnailUrl: null, type: '', uri: null, url: null, userHost: null, userId: null, webpublicAccessKey: null, webpublicUrl: null }),
	'admin/emoji/add': staticJson(SHAPE_12),
	'admin/emoji/copy': staticJson({ id: '' }),
	'admin/indie-auth/create': staticJson({ createdAt: '', id: '', name: null, redirectUris: [] }),
	'admin/meta': staticJson({ app192IconUrl: null, app512IconUrl: null, backgroundImageUrl: null, bannerUrl: null, blockedHosts: [], blockedRemoteCustomEmojis: [], cacheRemoteFiles: false, cacheRemoteSensitiveFiles: false, deeplAuthKey: null, deeplIsPro: false, defaultDarkTheme: null, defaultLightTheme: null, description: null, dimensions: 0, disableRegistration: false, email: null, emailRequiredForSignup: false, enableActiveEmailValidation: false, enableChartsForFederatedInstances: false, enableChartsForRemoteUser: false, enableEmail: false, enableFanoutTimeline: false, enableFanoutTimelineDbFallback: false, enableHcaptcha: false, enableIdenticonGeneration: false, enableIpLogging: false, enableMcaptcha: false, enableRecaptcha: false, enableSensitiveMediaDetectionForVideos: false, enableServerMachineStats: false, enableServiceWorker: false, enableTruemailApi: false, enableTurnstile: false, enableVerifymailApi: false, featuredGameChannels: [], federation: '', federationHosts: [], googleAnalyticsId: null, hcaptchaSecretKey: null, hcaptchaSiteKey: null, hiddenTags: [], iconUrl: null, impressumUrl: null, infoImageUrl: null, inquiryUrl: null, maintainerEmail: null, maintainerName: null, manifestJsonOverride: '', mascotImageUrl: null, mcaptchaInstanceUrl: null, mcaptchaSecretKey: null, mcaptchaSiteKey: null, name: null, notFoundImageUrl: null, notesPerOneAd: 0, objectStorageAccessKey: null, objectStorageBaseUrl: null, objectStorageBucket: null, objectStorageEndpoint: null, objectStoragePort: null, objectStoragePrefix: null, objectStorageRegion: null, objectStorageS3ForcePathStyle: false, objectStorageSecretKey: null, objectStorageSetPublicRead: false, objectStorageUseProxy: false, objectStorageUseSSL: false, perLocalUserUserTimelineCacheMax: 0, perRemoteUserUserTimelineCacheMax: 0, perUserHomeTimelineCacheMax: 0, perUserListTimelineCacheMax: 0, pinnedUsers: [], policies: {}, preservedUsernames: [], privacyPolicyUrl: null, prohibitedWords: [], prohibitedWordsForNameOfUser: [], proxyAccountId: '', recaptchaSecretKey: null, recaptchaSiteKey: null, repositoryUrl: null, sensitiveMediaDetection: '', sensitiveMediaDetectionSensitivity: '', sensitiveWords: [], serverErrorImageUrl: null, setSensitiveFlagAutomatically: false, shortName: null, smtpHost: null, smtpPass: null, smtpPort: null, smtpSecure: false, smtpUser: null, summalyProxy: null, swPrivateKey: null, swPublickey: null, themeColor: null, tosUrl: null, translatorAvailable: false, truemailAuthKey: null, truemailInstance: null, turnstileSecretKey: null, turnstileSiteKey: null, uri: '', urlPreviewDenyList: [], urlPreviewEnabled: false, urlPreviewMaximumContentLength: 0, urlPreviewRequireContentLength: false, urlPreviewSummaryProxyUrl: null, urlPreviewTimeout: 0, urlPreviewUserAgent: null, useObjectStorage: false, verifymailAuthKey: null, version: '', wellKnownWebsites: [] }),
	'admin/queue/stats': staticJson({ db: null, deliver: null, inbox: null, objectStorage: null }),
	'admin/relays/add': staticJson({ id: '', inbox: '', status: '' }),
	'admin/roles/create': staticJson(SHAPE_4),
	'admin/roles/show': staticJson(SHAPE_4),
	'admin/show-user': staticJson({ alwaysMarkNsfw: false, autoAcceptFollowed: false, autoSensitive: false, carefulBot: false, email: null, emailVerified: false, followedMessage: null, injectFeaturedNote: false, inlinePolicies: [], isDeleted: false, isHibernated: false, isLimited: false, isModerator: false, isSilenced: false, isSuspended: false, lastActiveDate: null, moderationNote: '', mutedInstances: [], mutedWords: [], noCrawle: false, notificationRecieveConfig: {}, policies: null, preventAiLearning: false, receiveAnnouncementEmail: false, roleAssigns: [], roles: [], signins: [] }),
	'admin/sso/create': staticJson({ acsUrl: '', audience: [], binding: '', createdAt: '', id: '', issuer: '', name: null, publicKey: '', signatureAlgorithm: '', type: '', wantAssertionsSigned: false, wantAuthnRequestsSigned: false, wantEmailAddressNormalized: false }),
	'admin/system-webhook/create': staticJson(SHAPE_5),
	'admin/system-webhook/show': staticJson(SHAPE_5),
	'admin/system-webhook/update': staticJson(SHAPE_5),
	'admin/update-proxy-account': staticJson(ME_DETAILED_STUB),
	'announcement': staticJsonPublic(SHAPE_13),
	'announcements/show': staticJsonPublic(SHAPE_13),
	'antennas/create': staticJson(SHAPE_6),
	'antennas/show': staticJson(SHAPE_6),
	'antennas/update': staticJson(SHAPE_6),
	'ap/show': staticJson({ object: null, type: null }),
	'app/create': staticJsonPublic(SHAPE_14),
	'app/show': staticJsonPublic(SHAPE_14),
	'auth/session/generate': staticJsonPublic({ token: '', url: '' }),
	'auth/session/show': staticJsonPublic({ app: null, id: '', token: '' }),
	'auth/session/userkey': staticJsonPublic({ accessToken: '', user: null }),
	'blocking/create': staticJson(USER_LITE_STUB),
	'blocking/delete': staticJson(USER_LITE_STUB),
	'channels/create': staticJson(SHAPE_7),
	'channels/show': staticJsonPublic(SHAPE_7),
	'channels/update': staticJson(SHAPE_7),
	'charts/active-users': staticJsonPublic({ read: [], readWrite: [], registeredOutsideMonth: [], registeredOutsideWeek: [], registeredOutsideYear: [], registeredWithinMonth: [], registeredWithinWeek: [], registeredWithinYear: [], write: [] }),
	'charts/ap-request': staticJsonPublic({ deliverFailed: [], deliverSucceeded: [], inboxReceived: [] }),
	'charts/drive': staticJsonPublic(SHAPE_1),
	'charts/federation': staticJsonPublic({ deliveredInstances: [], inboxInstances: [], pub: [], pubActive: [], pubsub: [], stalled: [], sub: [], subActive: [] }),
	'charts/instance': staticJsonPublic({ drive: {}, followers: {}, following: {}, notes: {}, requests: {}, users: {} }),
	'charts/notes': staticJsonPublic(SHAPE_1),
	'charts/user/drive': staticJsonPublic({ decCount: [], decSize: [], incCount: [], incSize: [], totalCount: [], totalSize: [] }),
	'charts/user/following': staticJsonPublic(SHAPE_1),
	'charts/user/notes': staticJsonPublic({ dec: [], diffs: {}, inc: [], total: [] }),
	'charts/user/pv': staticJsonPublic({ pv: {}, upv: {} }),
	'charts/user/reactions': staticJsonPublic(SHAPE_1),
	'charts/users': staticJsonPublic(SHAPE_1),
	'clips/create': staticJson(SHAPE_8),
	'clips/show': staticJsonPublic(SHAPE_8),
	'clips/update': staticJson(SHAPE_8),
	'drive': staticJson({ capacity: 0, usage: 0 }),
	'drive/files/create': staticJson(SHAPE_9),
	'drive/files/show': staticJson(SHAPE_9),
	'drive/files/update': staticJson(SHAPE_9),
	'drive/folders/create': staticJson(SHAPE_10),
	'drive/folders/show': staticJson(SHAPE_10),
	'drive/folders/update': staticJson(SHAPE_10),
	'email-address/available': staticJsonPublic({ available: false, reason: null }),
	'emoji': staticJsonPublic(SHAPE_12),
	'federation/stats': staticJsonPublic({ otherFollowersCount: 0, otherFollowingCount: 0, topPubInstances: [], topSubInstances: [] }),
	'fetch-external-resources': staticJson({ data: '', type: '' }),
	'fetch-rss': staticJsonPublic({ items: [] }),
	'flash/create': staticJson(SHAPE_15),
	'flash/show': staticJsonPublic(SHAPE_15),
	'following/create': staticJson(USER_LITE_STUB),
	'following/delete': staticJson(USER_LITE_STUB),
	'following/invalidate': staticJson(USER_LITE_STUB),
	'following/requests/cancel': staticJson(USER_LITE_STUB),
	'following/update': staticJson(USER_LITE_STUB),
	'gallery/posts/create': staticJson(SHAPE_11),
	'gallery/posts/show': staticJsonPublic(SHAPE_11),
	'gallery/posts/update': staticJson(SHAPE_11),
	'get-online-users-count': staticJsonPublic({ count: 0 }),
	'hashtags/show': staticJsonPublic({ attachedLocalUsersCount: 0, attachedRemoteUsersCount: 0, attachedUsersCount: 0, mentionedLocalUsersCount: 0, mentionedRemoteUsersCount: 0, mentionedUsersCount: 0, tag: '' }),
	'i/2fa/done': staticJson({ backupCodes: [] }),
	'i/2fa/key-done': staticJson({ id: '', name: '' }),
	'i/2fa/register': staticJson({ issuer: '', label: '', qr: '', secret: '', url: '' }),
	'i/2fa/register-key': staticJson({ attestation: null, authenticatorSelection: null, challenge: '', excludeCredentials: null, extensions: null, pubKeyCredParams: [], rp: {}, timeout: null, user: {} }),
	'i/pin': staticJson(ME_DETAILED_STUB),
	'i/registry/get-detail': staticJson({ updatedAt: '', value: null }),
	'i/unpin': staticJson(ME_DETAILED_STUB),
	'i/update-email': staticJson(ME_DETAILED_STUB),
	'i/webhooks/create': staticJson(SHAPE_16),
	'i/webhooks/show': staticJson(SHAPE_16),
	'invite/limit': staticJson({ remaining: null }),
	'miauth/gen-token': staticJson({ token: '' }),
	'pages/create': staticJson(SHAPE_17),
	'pages/show': staticJsonPublic(SHAPE_17),
	'reversi/show-game': staticJsonPublic({ black: null, bw: '', canPutEverywhere: false, createdAt: '', endedAt: null, form1: null, form2: null, id: '', isEnded: false, isLlotheo: false, isStarted: false, logs: [], loopedBoard: false, map: [], noIrregularRules: false, startedAt: null, surrenderedUserId: null, timeLimitForEachTurn: 0, timeoutUserId: null, user1: null, user1Id: '', user1Ready: false, user2: null, user2Id: '', user2Ready: false, winner: null, winnerId: null }),
	'reversi/verify': staticJsonPublic({ desynced: false }),
	'roles/show': staticJsonPublic(SHAPE_4),
	'sw/update-registration': staticJson({ endpoint: '', sendReadMessage: false, userId: '' }),
	'test': staticJsonPublic({ required: false }),
	'username/available': staticJsonPublic({ available: false }),
	'users/get-security-info': staticJsonPublic({ securityKeys: false, twoFactorEnabled: false, usePasswordLessLogin: false }),
	'users/get-skeb-status': staticJsonPublic({ clientRequestCount: 0, creatorRequestCount: 0, isAcceptable: false, isCreator: false, screenName: '', skills: [] }),
	'users/lists/create': staticJson(SHAPE_2),
	'users/lists/create-from-public': staticJson(SHAPE_2),
	'users/lists/show': staticJsonPublic(SHAPE_2),
	'users/lists/update': staticJson(SHAPE_2),
	'users/relation': staticJson({ hasPendingFollowRequestFromYou: null, hasPendingFollowRequestToYou: null, id: null, isBlocked: null, isBlocking: null, isFollowed: null, isFollowing: null, isMuted: null, isRenoteMuted: null }),
	'users/stats': staticJsonPublic({ driveFilesCount: 0, driveUsage: 0, followersCount: 0, followingCount: 0, localFollowersCount: 0, localFollowingCount: 0, noteFavoritesCount: 0, notesCount: 0, pageLikedCount: 0, pageLikesCount: 0, pollVotedCount: 0, pollVotesCount: 0, receivedReactionsCount: 0, remoteFollowersCount: 0, remoteFollowingCount: 0, renotedCount: 0, renotesCount: 0, repliedCount: 0, repliesCount: 0, sentReactionsCount: 0 }),
	'v2/admin/emoji/list': staticJson({ allCount: 0, allPages: 0, count: 0, emojis: [] }),
	// Boolean
	'drive/files/check-existence': staticJson(false),
};
