/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Auto-generated stub routes for unimplemented Misskey API endpoints.
 */

import type { Handler } from '../types.js';
import { json, requireUser } from '../helpers.js';

const noContent = (): Response =>
	new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': '*' } });

const emptyArr: Handler = async () => json([]);
const emptyObj: Handler = async () => json({});
const authedNoContent: Handler = async (db, body) => {
	const u = await requireUser(db, body); if (u instanceof Response) return u;
	return noContent();
};
const authedArr: Handler = async (db, body) => {
	const u = await requireUser(db, body); if (u instanceof Response) return u;
	return json([]);
};
const authedObj: Handler = async (db, body) => {
	const u = await requireUser(db, body); if (u instanceof Response) return u;
	return json({});
};

const chartResult: Handler = async () => json({ diffs: { normal: [], reply: [], renote: [], withFile: [] }, local: { normal: [], reply: [], renote: [], withFile: [] }, remote: { normal: [], reply: [], renote: [], withFile: [] } });

export const stubRoutes: Record<string, Handler> = {
	'admin/abuse-report-resolver/create': authedObj,
	'admin/abuse-report-resolver/delete': authedNoContent,
	'admin/abuse-report-resolver/list': authedArr,
	'admin/abuse-report-resolver/update': authedNoContent,
	'admin/abuse-report/notification-recipient/create': authedObj,
	'admin/abuse-report/notification-recipient/delete': authedNoContent,
	'admin/abuse-report/notification-recipient/list': authedArr,
	'admin/abuse-report/notification-recipient/show': authedObj,
	'admin/abuse-report/notification-recipient/update': authedObj,
	'admin/accounts/delete': authedNoContent,
	'admin/accounts/find-by-email': authedObj,
	'admin/accounts/pending/list': authedArr,
	'admin/accounts/pending/revoke': authedNoContent,
	'admin/ad/create': authedObj,
	'admin/ad/delete': authedNoContent,
	'admin/ad/list': authedArr,
	'admin/ad/update': authedNoContent,
	'admin/avatar-decorations/create': authedObj,
	'admin/avatar-decorations/delete': authedNoContent,
	'admin/avatar-decorations/list': authedArr,
	'admin/avatar-decorations/update': authedNoContent,
	'admin/captcha/current': authedObj,
	'admin/captcha/save': authedNoContent,
	'admin/drive/clean-remote-files': authedNoContent,
	'admin/drive/cleanup': authedNoContent,
	'admin/drive/delete-all-files-of-a-user': authedNoContent,
	'admin/drive/files': authedArr,
	'admin/drive/show-file': authedObj,
	'admin/emoji/add': authedObj,
	'admin/emoji/add-aliases-bulk': authedNoContent,
	'admin/emoji/copy': authedObj,
	'admin/emoji/delete': authedNoContent,
	'admin/emoji/delete-bulk': authedNoContent,
	'admin/emoji/import-zip': authedNoContent,
	'admin/emoji/list': authedArr,
	'admin/emoji/list-remote': authedArr,
	'admin/emoji/remove-aliases-bulk': authedNoContent,
	'admin/emoji/set-aliases-bulk': authedNoContent,
	'admin/emoji/set-category-bulk': authedNoContent,
	'admin/emoji/set-license-bulk': authedNoContent,
	'admin/emoji/update': authedNoContent,
	'admin/federation/delete-all-files': authedNoContent,
	'admin/federation/refresh-remote-instance-metadata': authedNoContent,
	'admin/federation/remove-all-following': authedNoContent,
	'admin/federation/update-instance': authedNoContent,
	'admin/get-user-ips': authedArr,
	'admin/indie-auth/create': authedObj,
	'admin/indie-auth/delete': authedNoContent,
	'admin/indie-auth/list': authedArr,
	'admin/indie-auth/update': authedNoContent,
	'admin/promo/create': authedNoContent,
	'admin/queue/clear': authedNoContent,
	'admin/queue/deliver-delayed': authedArr,
	'admin/queue/inbox-delayed': authedArr,
	'admin/queue/promote': authedNoContent,
	'admin/queue/stats': authedObj,
	'admin/relays/add': authedObj,
	'admin/relays/list': authedArr,
	'admin/relays/remove': authedNoContent,
	'admin/send-email': authedNoContent,
	'admin/sso/create': authedObj,
	'admin/sso/delete': authedNoContent,
	'admin/sso/list': authedArr,
	'admin/sso/update': authedNoContent,
	'admin/system-webhook/create': authedObj,
	'admin/system-webhook/delete': authedNoContent,
	'admin/system-webhook/list': authedArr,
	'admin/system-webhook/show': authedObj,
	'admin/system-webhook/test': authedNoContent,
	'admin/system-webhook/update': authedObj,
	'admin/unset-user-mutual-link': authedNoContent,
	'admin/update-proxy-account': authedObj,
	'ap/get': authedObj,
	'ap/show': authedObj,
	'app/create': emptyObj,
	'app/show': emptyObj,
	'auth/accept': authedNoContent,
	'auth/session/generate': emptyObj,
	'auth/session/show': emptyObj,
	'auth/session/userkey': emptyObj,
	'charts/active-users': chartResult,
	'charts/ap-request': chartResult,
	'charts/drive': chartResult,
	'charts/federation': chartResult,
	'charts/instance': chartResult,
	'charts/notes': chartResult,
	'charts/user/drive': chartResult,
	'charts/user/following': chartResult,
	'charts/user/notes': chartResult,
	'charts/user/pv': chartResult,
	'charts/user/reactions': chartResult,
	'charts/users': chartResult,
	'drive': authedObj,
	'drive/files/attached-notes': authedArr,
	'drive/files/check-existence': authedObj,
	'drive/files/create': authedObj,
	'drive/files/delete': authedNoContent,
	'drive/files/find': authedArr,
	'drive/files/find-by-hash': authedArr,
	'drive/files/show': authedObj,
	'drive/files/update': authedObj,
	'drive/files/upload-from-url': authedNoContent,
	'drive/folders/create': authedObj,
	'drive/folders/delete': authedNoContent,
	'drive/folders/find': authedArr,
	'drive/folders/show': authedObj,
	'drive/folders/update': authedObj,
	'drive/stream': authedArr,
	'export-custom-emojis': authedNoContent,
	'federation/followers': emptyArr,
	'federation/following': emptyArr,
	'federation/instances': emptyArr,
	'federation/show-instance': async () => noContent(),
	'federation/stats': emptyObj,
	'federation/update-remote-user': async () => noContent(),
	'federation/users': emptyArr,
	'i/2fa/done': authedObj,
	'i/2fa/key-done': authedObj,
	'i/2fa/password-less': authedNoContent,
	'i/2fa/register': authedObj,
	'i/2fa/register-key': authedObj,
	'i/2fa/remove-key': authedNoContent,
	'i/2fa/unregister': authedNoContent,
	'i/2fa/update-key': authedNoContent,
	'i/apps': authedArr,
	'i/authorized-apps': authedArr,
	'i/export-antennas': authedNoContent,
	'i/export-blocking': authedNoContent,
	'i/export-clips': authedNoContent,
	'i/export-favorites': authedNoContent,
	'i/export-following': authedNoContent,
	'i/export-mute': authedNoContent,
	'i/export-notes': authedNoContent,
	'i/export-user-lists': authedNoContent,
	'i/import-antennas': authedNoContent,
	'i/import-blocking': authedNoContent,
	'i/import-following': authedNoContent,
	'i/import-muting': authedNoContent,
	'i/import-user-lists': authedNoContent,
	'i/update-email': authedObj,
	'i/webhooks/create': authedObj,
	'i/webhooks/delete': authedNoContent,
	'i/webhooks/list': authedArr,
	'i/webhooks/show': authedObj,
	'i/webhooks/test': authedNoContent,
	'i/webhooks/update': authedNoContent,
	'miauth/gen-token': authedObj,
	'my/apps': authedArr,
	'notes': emptyArr,
	'notes/scheduled/cancel': authedNoContent,
	'notes/scheduled/list': authedArr,
	'notes/translate': authedNoContent,
	'notifications/test-notification': authedNoContent,
	'reversi/cancel-match': authedNoContent,
	'reversi/games': emptyArr,
	'reversi/invitations': authedArr,
	'reversi/match': authedNoContent,
	'reversi/show-game': emptyObj,
	'reversi/surrender': authedNoContent,
	'reversi/verify': emptyObj,
	'users/get-skeb-status': emptyObj,
	'v2/admin/emoji/list': authedObj,
};
