/*
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { Handler } from '../types.js';
import { json, err, requireUser, getMetaAll } from '../helpers.js';

export const adminMeta: Handler = async (db, body) => {
	const u = await requireUser(db, body);
	if (u instanceof Response) return u;
	if (!u.is_admin) return err('Forbidden', 403);

	const m = await getMetaAll(db);
	const parseMeta = (key: string): unknown => {
		const raw = m[key];
		if (raw == null) return undefined;
		try { return JSON.parse(raw); } catch { return raw; }
	};
	const metaObj: Record<string, unknown> = {
		name: parseMeta('name') ?? 'Misslite',
		description: parseMeta('description') ?? '',
		themeColor: parseMeta('themeColor') ?? '#86b300',
		maxNoteTextLength: Number(parseMeta('maxNoteLength') ?? 3000),
		registrationMode: parseMeta('registrationMode') ?? 'invite',
		bannerUrl: parseMeta('bannerUrl') ?? null,
		iconUrl: parseMeta('iconUrl') ?? null,
		backgroundImageUrl: parseMeta('backgroundImageUrl') ?? null,
		maintainerName: parseMeta('maintainerName') ?? 'admin',
		maintainerEmail: parseMeta('maintainerEmail') ?? '',
		emailRequiredForSignup: false,
		enableHcaptcha: false, hcaptchaSiteKey: null,
		enableMcaptcha: false, mcaptchaSiteKey: null, mcaptchaInstanceUrl: null,
		enableRecaptcha: false, recaptchaSiteKey: null,
		enableTurnstile: false, turnstileSiteKey: null,
		enableTestcaptcha: false,
		objectStorageBaseUrl: null,
		objectStorageBucket: null,
		objectStoragePrefix: null,
		objectStorageEndpoint: null,
		objectStorageRegion: null,
		objectStoragePort: null,
		objectStorageAccessKey: null,
		objectStorageSecretKey: null,
		objectStorageUseSSL: true,
		objectStorageUseProxy: false,
		objectStorageSetPublicRead: false,
		objectStorageS3ForcePathStyle: true,
		useObjectStorage: false,
		sensitiveMediaDetection: 'none',
		sensitiveMediaDetectionSensitivity: 'medium',
		setSensitiveFlagAutomatically: false,
		enableSensitiveMediaDetectionForVideos: false,
		enableIpLogging: false,
		enableActiveEmailValidation: false,
		enableChartsForRemoteUser: false,
		enableChartsForFederatedInstances: false,
		enableServerMachineStats: false,
		enableIdenticonGeneration: true,
		cacheRemoteFiles: true,
		cacheRemoteSensitiveFiles: true,
		policies: {},
		pinnedUsers: [],
		hiddenTags: [],
		blockedHosts: [],
		silencedHosts: [],
		mediaSilencedHosts: [],
		sensitiveWords: [],
		prohibitedWords: [],
		preservedUsernames: [],
		deeplAuthKey: null,
		deeplIsPro: false,
		enableEmail: false,
		email: null,
		smtpSecure: false,
		smtpHost: null,
		smtpPort: null,
		smtpUser: null,
		smtpPass: null,
		swPublickey: null,
		swPrivateKey: null,
		enableServiceWorker: false,
		translatorAvailable: false,
		proxyAccountId: null,
		googleAnalyticsId: null,
		mascotImageUrl: null,
		serverErrorImageUrl: null,
		infoImageUrl: null,
		notFoundImageUrl: null,
		app192IconUrl: null,
		app512IconUrl: null,
		blockedRemoteCustomEmojis: [],
		hcaptchaSecretKey: null,
		mcaptchaSecretKey: null,
		recaptchaSecretKey: null,
		turnstileSecretKey: null,
		enableVerifymailApi: false,
		verifymailAuthKey: null,
		enableTruemailApi: false,
		truemailInstance: null,
		truemailAuthKey: null,
		manifestJsonOverride: null,
		enableFanoutTimeline: true,
		enableFanoutTimelineDbFallback: true,
		perLocalUserUserTimelineCacheMax: 300,
		perRemoteUserUserTimelineCacheMax: 100,
		perUserHomeTimelineCacheMax: 100,
		perUserListTimelineCacheMax: 100,
		notesPerOneAd: 0,
		wellKnownWebsites: [],
		urlPreviewDenyList: [],
		featuredGameChannels: [],
		dimensions: null,
		disableRegistration: false,
		impressumUrl: null,
		privacyPolicyUrl: null,
		repositoryUrl: 'https://github.com/cyanmint/misslite',
		tosUrl: null,
		donationUrl: null,
		feedbackUrl: null,
		shortName: null,
		summalyProxy: null,
		uri: '',
		urlPreviewEnabled: true,
		urlPreviewTimeout: 10000,
		urlPreviewMaximumContentLength: 1048576,
		urlPreviewRequireContentLength: true,
		urlPreviewUserAgent: null,
		urlPreviewSummaryProxyUrl: null,
		federation: true,
		federationHosts: [],
		prohibitedWordsForNameOfUser: [],
		inquiryUrl: null,
		defaultDarkTheme: null,
		defaultLightTheme: null,
		version: '2026.3.0',
	};
	for (const key of Object.keys(metaObj)) {
		const parsed = parseMeta(key);
		if (parsed !== undefined) metaObj[key] = parsed;
	}
	return json(metaObj);
};
