name = "misslite-cf"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "misslite"
database_id = "placeholder-change-me"

[vars]
INITIAL_PASSWORD = "changeme"
